### ISSUE TITLE
Inheriting hash methods from Object

### ISSUE THREAD

**Issue by eccabay** [kyleacmooney/A1-part2#2]
In your Object spec, you have `size_t hash` and `virtual size_t getHash_`, implying that the `hash` method should stay the same for each class that inherits from object and should write their own `getHash()` method. However, both your Array and String methods have `hash()` but not `getHash()`. Can you change this for consistency (so Array and String have `getHash()` instead)? 
Also, to match with specs from the rest of the class, can you rename `getHash()` to be `hash_me()`?"

**Comment by kyleacmooney** [comment]
We are going to remove the hash field from Object.h and make hash() virtual instead?  The utility class that was given to us by the instructors on piazza (which we were following) turns out to be incorrect.  Vitek's response in this piazza post recommends making hash() virtual:

https://piazza.com/class/k51bluky59n2jr?cid=248

I'm not sure what the function of hash_me()/getHash() would be in that case, but regardless I don't think it needs to stay in our API---if you need those helpers you can implement those helpers/name them whatever you want as "private" methods.

**Comment by eccabay** [comment]
Sounds good - as long as all three methods have matching specs, we can work with it! Thanks.

**Comment by rishmathur21** [comment]
Actually -- turns out our Queue designers require the 'compute_hash/hash_me' method in their Object.h.
Can you replace your getHash() method with 'virtual void compute_hash()', instead of getting rid of it? It's really just a naming thing...

Thanks!

**Comment by kyleacmooney** [comment]
"Actually -- turns out our Queue designers require the 'compute_hash/hash_me' method in their Object.h.
Can you replace your getHash() method with 'virtual void compute_hash()', instead of getting rid of it? It's really just a naming thing..."

Hmmm... I don't mean to cause any issues, just curious what the functionality of a mandated hash helper like that would be in this case.  Without a cached hash value, our object class needs only to implement hashing in the (now-virtual) hash() method.   If it really is just to meet the spec of the object.h for @rishmathur21 's Queue designers, I don't mind adding it, but I worry about causing a cascading problem for anyone else who is using this API.  In that case, I feel like the API that makes the most sense should get precedence.  It would be cool to know how many groups are using this so I know whether or not that actually would cause any issues.   Are you both in the same group @eccabay and @rishmathur21 ?

**Comment by kyleacmooney** [comment]
Very much related thought: I don't actually think you having such a helper (hash_me, get_hash, compute_hash, etc.) in your object.h would be a problem.  You'd still technically be implementing our API, just with the use of a helper.  And you'd also be implementing the Queue designer's API.  Let me know what you think.
